config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :employees do
    resources :requests
  end
  root 'welcome_page#index' 
  get '/requests', to: 'employees#index'

  
  

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :requests, dependent: :destroy
  validates :name, presence: true,
                    length: { minimum: 6 }
  validates :email, presence: true,
                    length: { minimum: 8 }
  
      # It returns the employees whose name contain one or more words inc. in search
  def self.search(query)
    # where(:name, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%") 
  end

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :employee
  validates :hol_start_date, :hol_end_date, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # to override pdefault devise path for "after sign in/up"
  def after_sign_in_path_for(resource)
    employees_path
  end
  
  def after_sign_up_path_for(resource)
    employees_path
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!, except: [:create, :edit] 
  
  def index
    # to show all employees under /index path
    #search by name and return results
        if params[:search]
          @employees = Employee.search(params[:search])
        else 
          @employees = Employee.all
        end
  end
  

  
  
 # to show 1 employee 
  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end
  
  def edit
    @employee = Employee.find(params[:id])
  end

  # action to create an employee
  def create
    
    @employee = Employee.new(employee_params)
 
      if @employee.save
        redirect_to @employee
      else
        render 'new'
      end

  end
  
  # to edit employee details
  def update
    @employee = Employee.find(params[:id])
 
      if @employee.update(employee_params)
        redirect_to @employee
      else
        render 'edit'
      end
  end
 
 # to remove employee
  def destroy
      @employee = Employee.find(params[:id])
      @employee.destroy
 
      redirect_to employees_path
  end

  # whitelist of controller paramaters to allow them access
  private
    def employee_params
      params.require(:employee).permit(:name, :email, :address, :start_date)
    end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  
  def create
    @employee = Employee.find(params[:employee_id])
    @request = @employee.requests.create(request_params)
    redirect_to employee_path(@employee) 
  end  
  
  def destroy
    @employee = Employee.find(params[:employee_id])
    @request = @employee.requests.find(params[:id])
    @request.destroy
    redirect_to employee_path(@employee)
  end
  
    
  private
    def request_params
      params.require(:request).permit(:hol_start_date, :hol_end_date, :comment)
    end

end

app/controllers/welcome_page_controller.rb
class WelcomePageController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/welcome_page_helper.rb
module WelcomePageHelper
end

app/views/employees/edit.html.erb
<h1>Editing employee</h1>
 
<%= form_for :employee, url: employee_path(@employee), method: :patch do |f| %>
 
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@employee.errors.count, "error") %> prohibited
        this employee from being saved:
      </h2>
      <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
<p>
    <%= f.label :Name %><br> 	
    <%= f.text_field :name %>	
  </p>
 <p>
    <%= f.label :Email %><br>
    <%= f.text_field :email %>
 </p>
    
   <p>
    <%= f.label :Address %><br>
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.label :start_date, "Start date; format YYYY-MM-DD)" %><br>
    <%= f.date_field :start_date %>
  </p>
 
  <p>
    <%= f.submit %>
    <%= link_to 'Go back', employees_path %>
  </p>
<% end %>

app/views/employees/index.html.erb
<h1>List of Employees</h1>


      <%= form_tag(employees_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Employee" %>
      <%= submit_tag("Search/Show All") %>
      <% end %>

<table>
  <table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Address</th>
    <th>Start date</th>
  </tr>
  </thead>
  
  <% @employees.each do |employee| %>
  <tbody>
    <tr>
      <td><%= employee.name %></td>
      <td><%= employee.email %></td>
      <td><%= employee.address %></td>
      <td><%= employee.start_date %></td>
      <td><%= link_to 'Show details', employee_path(employee) %></td>  
      <td><%= link_to 'Update details', edit_employee_path(employee) %></td>
      <td><%= link_to 'Remove', employee_path(employee),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
    </tr>
  </tbody>
  <% end %>
  <td><%= link_to 'Add new employee', new_employee_path %></td>
  
</table>

app/views/employees/new.html.erb
<%# creates form to add new employee %> 
<h1>New Employee</h1>
<%= form_for :employee, url: employees_path do |f| %>

 <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@employee.errors.count, "error") %> prohibited
        this employee from being saved:
      </h2>
      <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :Name %><br> 	
    <%= f.text_field :name %>	
  </p>
 <p>
    <%= f.label :Email %><br>
    <%= f.text_field :email %>
 </p>
    
   <p>
    <%= f.label :Address %><br>
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.label :start_date, "Start date (YYYY-MM-DD):" %><br>
    <%= f.date_field :start_date %>
  </p>
 
  <p>
    <%= f.submit %>
    <%= link_to 'Go Back', employees_path %>
  </p>
<% end %>

app/views/employees/show.html.erb
<h1>Employee Profile</h1>
<%# shows created employee %> 

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>
 
<p>
  <strong>Started on:</strong>
  <%= @employee.start_date %>
</p>
</table>
<h2>Previous Requests</h2>

<table>
  <table class="table">
  <thead>
    <tr>
    <th>Start date:</th>
    <th>End date:</th>
    <th>Comment:</th>
    </tr>
  </thead>
  <% @employee.requests.each do |request| %>
  <tbody>
    <tr>
    <td><%= request.hol_start_date %></td>
    <td><%= request.hol_end_date %></td>
    <td><%= request.comment %></td>
    <td><%= link_to 'Delete Request', [request.employee, request],
               method: :delete,
               data: { confirm: 'Are you sure?' } %></td>
    </tr>
  </tbody>
  <% end %>
  </table>


<h2>Add a new holiday request</h2>
<h2>(yyyy-mm-dd)</h2> 
<%= form_for([@employee, @employee.requests.build]) do |f| %>
  <p>
    <%= f.label :hol_start_date, "Holiday start date" %><br> 
    <%= f.text_field :hol_start_date %>
  </p>
  <p>
    <%= f.label :hol_end_date, "Holiday end date" %><br> 
    <%= f.text_field :hol_end_date %>
  </p>
  <p>
    <%= f.label :comment %><br> 
    <%= f.text_area :comment %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <p><%= link_to 'Edit', edit_employee_path(@employee) %> |
      <%= link_to 'Back', employees_path %>
  </p>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Holiday App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Holiday App", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-centre">
            <li><%= link_to "Register", new_user_registration_path %></li>
            <li><%= link_to "Login", user_session_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            
            

          </ul>
        </nav>
      </div>
    </header>
    
    <div class="container">
      <div class="center jumbotron">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>

    </div>
    <footer class="footer">
  <small>
    <h6>Powered by x14126681</h6>
  </small>

</footer>
    </div>
</body>
</html>

app/views/welcome_page/index.html.erb
<div class="center jumbotron">
<h1>Welcome to Holiday App</h1>

<h3>To manage your employees and their holidays </h3>
<table>
  <table class="table">
  <thead>
  <tr>
    <%= render 'devise/welcome/login_items' %>
    or
    <%= render 'devise/welcome/registration_items' %>
    </thead>
</table>

</div>